// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhmmngrqyynnpbzzqiom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZobW1uZ3JxeXlubnBienpxaW9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MTUzNDcsImV4cCI6MjA2NzA5MTM0N30.-sQ0Gj6FJAQDxTST52KiGgrpwOBoRuCRGk-m_MWVK_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});